// Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.0.6262, generator: {generator})
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

namespace Commvault.Powershell.Models
{
    using static Commvault.Powershell.Runtime.Extensions;

    /// <summary>EnvironmentSetupRequest</summary>
    public partial class EnvironmentSetupRequest :
        Commvault.Powershell.Models.IEnvironmentSetupRequest,
        Commvault.Powershell.Models.IEnvironmentSetupRequestInternal
    {

        /// <summary>Backing field for <see cref="Password" /> property.</summary>
        private string _password;

        [Commvault.Powershell.Origin(Commvault.Powershell.PropertyOrigin.Owned)]
        public string Password { get => this._password; set => this._password = value; }

        /// <summary>Backing field for <see cref="Username" /> property.</summary>
        private string _username;

        [Commvault.Powershell.Origin(Commvault.Powershell.PropertyOrigin.Owned)]
        public string Username { get => this._username; set => this._username = value; }

        /// <summary>Backing field for <see cref="WebServerUrl" /> property.</summary>
        private string _webServerUrl;

        [Commvault.Powershell.Origin(Commvault.Powershell.PropertyOrigin.Owned)]
        public string WebServerUrl { get => this._webServerUrl; set => this._webServerUrl = value; }

        /// <summary>Creates an new <see cref="EnvironmentSetupRequest" /> instance.</summary>
        public EnvironmentSetupRequest()
        {

        }
    }
    /// EnvironmentSetupRequest
    public partial interface IEnvironmentSetupRequest :
        Commvault.Powershell.Runtime.IJsonSerializable
    {
        [Commvault.Powershell.Runtime.Info(
        Required = true,
        ReadOnly = false,
        Description = @"",
        SerializedName = @"password",
        PossibleTypes = new [] { typeof(string) })]
        string Password { get; set; }

        [Commvault.Powershell.Runtime.Info(
        Required = true,
        ReadOnly = false,
        Description = @"",
        SerializedName = @"username",
        PossibleTypes = new [] { typeof(string) })]
        string Username { get; set; }

        [Commvault.Powershell.Runtime.Info(
        Required = true,
        ReadOnly = false,
        Description = @"",
        SerializedName = @"WebServerURL",
        PossibleTypes = new [] { typeof(string) })]
        string WebServerUrl { get; set; }

    }
    /// EnvironmentSetupRequest
    internal partial interface IEnvironmentSetupRequestInternal

    {
        string Password { get; set; }

        string Username { get; set; }

        string WebServerUrl { get; set; }

    }
}