// Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.0.6262, generator: {generator})
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

namespace Commvault.Powershell.Models
{
    using static Commvault.Powershell.Runtime.Extensions;

    /// <summary>LoginResponse</summary>
    public partial class LoginResponse :
        Commvault.Powershell.Models.ILoginResponse,
        Commvault.Powershell.Models.ILoginResponseInternal
    {
        /// <summary>Backing field for <see cref="SmtpAddress" /> property.</summary>
        private string _smtpAddress;

        [Commvault.Powershell.Origin(Commvault.Powershell.PropertyOrigin.Owned)]
        public string SmtpAddress { get => this._smtpAddress; set => this._smtpAddress = value; }

        /// <summary>Backing field for <see cref="Token" /> property.</summary>
        private string _token;

        [Commvault.Powershell.Origin(Commvault.Powershell.PropertyOrigin.Owned)]
        public string Token { get => this._token; set => this._token = value; }

        /// <summary>Backing field for <see cref="UserName" /> property.</summary>
        private string _userName;

        [Commvault.Powershell.Origin(Commvault.Powershell.PropertyOrigin.Owned)]
        public string UserName { get => this._userName; set => this._userName = value; }

        /// <summary>Creates an new <see cref="LoginResponse" /> instance.</summary>
        public LoginResponse()
        {

        }
    }
    /// LoginResponse
    public partial interface ILoginResponse :
        Commvault.Powershell.Runtime.IJsonSerializable
    {

        [Commvault.Powershell.Runtime.Info(
        Required = true,
        ReadOnly = false,
        Description = @"",
        SerializedName = @"smtpAddress",
        PossibleTypes = new [] { typeof(string) })]
        string SmtpAddress { get; set; }

        [Commvault.Powershell.Runtime.Info(
        Required = true,
        ReadOnly = false,
        Description = @"",
        SerializedName = @"token",
        PossibleTypes = new [] { typeof(string) })]
        string Token { get; set; }

        [Commvault.Powershell.Runtime.Info(
        Required = true,
        ReadOnly = false,
        Description = @"",
        SerializedName = @"userName",
        PossibleTypes = new [] { typeof(string) })]
        string UserName { get; set; }

    }
    /// LoginResponse
    internal partial interface ILoginResponseInternal

    {
        

        string SmtpAddress { get; set; }

        string Token { get; set; }

        string UserName { get; set; }

    }
}